//User administration action types

export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_USER = 'GET_USER'
export const EDIT_USER_START = 'EDIT_USER_START'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL'




//Items Action Types
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS'
export const GET_ITEM = 'GET_ITEM'
export const RESERVE_ITEM_START = 'RESERVE_ITEM_START'
export const RESERVE_ITEM_SUCCESS = 'RESERVE_ITEM_SUCCESS'
export const RESERVE_ITEM_FAIL = 'RESERVE_ITEM_FAIL'
export const SET_ITEM_AS_TAKEN = 'SET_ITEM_AS_TAKEN'
export const ADD_ITEM_START = 'ADD_ITEM_START'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL'
export const SAVE_NEW_SLOTS_START = 'SAVE_NEW_SLOTS_START'
export const SAVE_NEW_SLOTS_SUCCESS = 'SAVE_NEW_SLOTS_SUCCESS'
export const SAVE_NEW_SLOTS_FAIL = 'SAVE_NEW_SLOTS_FAIL'
export const GET_SEARCH_ITEMS_RESULTS = 'GET_SEARCH_ITEMS_RESULTS'
export const SEARCH_ITEMS_START = 'SEARCH_ITEMS_START'
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS'
export const SEARCH_ITEMS_FAIL = 'SEARCH_ITEMS_FAIL'
export const DELETE_ITEM_START = 'DELETE_ITEM_START'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL'
export const USER_HAS_TRADING_ITEMS = 'USER_HAS_TRADING_ITEMS'
